CREATE DATABASE IF NOT EXISTS `typoglyph`;
USE `typoglyph`;

DROP TABLE IF EXISTS `puzzles`;
CREATE TABLE `puzzles` (
  `_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sentence` TEXT NOT NULL,
  `options` TEXT NOT NULL
);
